export const GET_WORKING_LISTS = 'GET_WORKING_LISTS';
export const SELECT_WORKING_LIST = 'SELECT_WORKING_LIST';
export const GET_WORKING_LIST_STUDIES = 'GET_WORKING_LIST_STUDIES';
export const SET_STUDY_INDEX = 'SET_STUDY_INDEX';
