export const GET_WORKING_LISTS = 'GET_WORKING_LISTS';
export const SELECT_WORKING_LIST = 'SELECT_WORKING_LIST';
export const GET_WORKING_LIST_STUDIES = 'GET_WORKING_LIST_STUDIES';
export const SET_STUDY_INDEX = 'SET_STUDY_INDEX';
export const SELECT_STUDY = 'SELECT_STUDY';
export const SET_REVIEW_STATUS = 'SET_REVIEW_STATUS';

export const SELECT_LOCATION = 'SELECT_LOCATION';
export const SET_LANDMARK_TOOL_SELECTION_STATUS =
  'SET_LANDMARK_TOOL_SELECTION_STATUS';
